<?php

return [
    'roles' => [
        'admin' => 'Administrator Cabang',
        'ketcab' => 'Ketua Cabang',
        'sekcab' => 'Sekretaris Cabang',
        'bencab' => 'Bendahara Cabang',
        'sekfung_medko' => 'Sekretaris Fungsi Media dan Komunikasi',
        'operator' => 'Operator Data & Warta',
    ],

    // Matriks Hak Akses (Permissions Matrix)
    'permissions' => [
        'admin' => [
            'dashboard.view',
            'dashboard.pengawas',
            'civitas.view',
            'civitas.create',
            'civitas.update',
            'civitas.delete',
            'civitas.import',
            'civitas.export',
            'news.view',
            'news.create',
            'news.update',
            'news.delete',
            'organization.view',
            'organization.update',
            'statistics.view',
            'users.view',
            'users.create',
            'users.update',
            'users.delete',
            'security.audit_log',
            'security.threats',
            'backup.view',
            'backup.create',
            'backup.download',
            'coordination.view',
            'coordination.manage',
        ],
        'operator' => [
            'dashboard.view',
            'civitas.view',
            'civitas.create',
            'civitas.update',
            'civitas.import',
            'civitas.export',
            'news.view',
            'news.create',
            'news.update',
            'statistics.view',
        ],
        'ketcab' => [
            'dashboard.pengawas',
            'civitas.view',
            'civitas.export',
            'news.view',
            'organization.view',
            'statistics.view',
            'reports.view',
            'reports.download',
            'coordination.view',
            'coordination.manage',
            'strategy.view',
            'strategy.manage',
            'security.audit_log',
        ],
        'sekcab' => [
            'dashboard.view',
            'civitas.view',
            'civitas.create',
            'civitas.update',
            'civitas.delete',
            'civitas.import',
            'civitas.export',
            'inventory.view',
            'inventory.manage',
            'archive.view',
            'archive.manage',
            'coordination.view',
            'coordination.manage',
            'statistics.view',
        ],
        'bencab' => [
            'dashboard.view',
            'finance.view',
            'finance.manage',
            'reports.download',
            'coordination.view',
            'coordination.manage',
        ],
        'sekfung_medko' => [
            'dashboard.view',
            'news.view',
            'news.create',
            'news.update',
            'news.delete',
            'statistics.view',
            'coordination.view',
            'coordination.manage',
        ],
    ],
];
