ServerRoot "E:/WebProgBPNama/apache2"
PidFile "logs/gmki-httpd.pid"
Listen 127.0.0.1:8000
ServerName 127.0.0.1:8000

Timeout 60
KeepAlive On
MaxKeepAliveRequests 100
KeepAliveTimeout 2
ThreadsPerChild 32
MaxRequestsPerChild 0

ServerTokens Prod
ServerSignature Off
TraceEnable Off

LoadModule actions_module modules/mod_actions.so
LoadModule alias_module modules/mod_alias.so
LoadModule authz_default_module modules/mod_authz_default.so
LoadModule authz_host_module modules/mod_authz_host.so
LoadModule cgi_module modules/mod_cgi.so
LoadModule dir_module modules/mod_dir.so
LoadModule env_module modules/mod_env.so
LoadModule headers_module modules/mod_headers.so
LoadModule log_config_module modules/mod_log_config.so
LoadModule mime_module modules/mod_mime.so
LoadModule rewrite_module modules/mod_rewrite.so

RewriteEngine On
RewriteCond %{THE_REQUEST} \s/+php-cgi/ [NC]
RewriteRule ^/php-cgi/ - [F,L]

TypesConfig conf/mime.types
DirectoryIndex index.php
DocumentRoot "E:/WebProgBPNama/www/gmkicabangpadang/frontend/public"

<Directory "E:/WebProgBPNama/www/gmkicabangpadang/frontend/public">
    Options FollowSymLinks
    AllowOverride All
    Order allow,deny
    Allow from all
</Directory>

ScriptAlias /php-cgi/ "E:/WebProgBPNama/php8/"
<Directory "E:/WebProgBPNama/php8">
    Options ExecCGI
    AllowOverride None
    Order allow,deny
    Allow from all
</Directory>

AddHandler application/x-httpd-php .php
Action application/x-httpd-php /php-cgi/php-cgi.exe
SetEnv PHPRC "E:/WebProgBPNama/php8"
SetEnv PHP_INI_SCAN_DIR "E:/WebProgBPNama/www/gmkicabangpadang/tools/apache/php-conf"

LogFormat "%h %l %u %t \"%r\" %>s %b" common
ErrorLog logs/gmki-error.log
LogLevel warn
CustomLog logs/gmki-access.log common
